// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CanAutoDNSSEC-0]
	_ = x[CanConcur-1]
	_ = x[CanGetZones-2]
	_ = x[CanOnlyDiff1Features-3]
	_ = x[CanUseAKAMAICDN-4]
	_ = x[CanUseAKAMAITLC-5]
	_ = x[CanUseAlias-6]
	_ = x[CanUseAzureAlias-7]
	_ = x[CanUseCAA-8]
	_ = x[CanUseDHCID-9]
	_ = x[CanUseDNAME-10]
	_ = x[CanUseDS-11]
	_ = x[CanUseDSForChildren-12]
	_ = x[CanUseHTTPS-13]
	_ = x[CanUseLOC-14]
	_ = x[CanUseNAPTR-15]
	_ = x[CanUsePTR-16]
	_ = x[CanUseRoute53Alias-17]
	_ = x[CanUseRP-18]
	_ = x[CanUseSMIMEA-19]
	_ = x[CanUseSOA-20]
	_ = x[CanUseSRV-21]
	_ = x[CanUseSSHFP-22]
	_ = x[CanUseSVCB-23]
	_ = x[CanUseTLSA-24]
	_ = x[CanUseDNSKEY-25]
	_ = x[CanUseOPENPGPKEY-26]
	_ = x[DocCreateDomains-27]
	_ = x[DocDualHost-28]
	_ = x[DocOfficiallySupported-29]
	_ = x[IsRegistrar-30]
	_ = x[IsDnsServiceProvider-31]
}

const _Capability_name = "CanAutoDNSSECCanConcurCanGetZonesCanOnlyDiff1FeaturesCanUseAKAMAICDNCanUseAKAMAITLCCanUseAliasCanUseAzureAliasCanUseCAACanUseDHCIDCanUseDNAMECanUseDSCanUseDSForChildrenCanUseHTTPSCanUseLOCCanUseNAPTRCanUsePTRCanUseRoute53AliasCanUseRPCanUseSMIMEACanUseSOACanUseSRVCanUseSSHFPCanUseSVCBCanUseTLSACanUseDNSKEYCanUseOPENPGPKEYDocCreateDomainsDocDualHostDocOfficiallySupportedIsRegistrarIsDnsServiceProvider"

var _Capability_index = [...]uint16{0, 13, 22, 33, 53, 68, 83, 94, 110, 119, 130, 141, 149, 168, 179, 188, 199, 208, 226, 234, 246, 255, 264, 275, 285, 295, 307, 323, 339, 350, 372, 383, 403}

func (i Capability) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Capability_index)-1 {
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Capability_name[_Capability_index[idx]:_Capability_index[idx+1]]
}
