// Code generated by "stringer -type DualHostSupport -trimprefix DualHostSupport"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DualHostSupportNotSupported-0]
	_ = x[DualHostSupportUntested-1]
	_ = x[DualHostSupportUnimplemented-2]
	_ = x[DualHostSupportAdditionsOnly-3]
	_ = x[DualHostSupportItsComplicated-4]
	_ = x[DualHostSupportFull-5]
}

const _DualHostSupport_name = "NotSupportedUntestedUnimplementedAdditionsOnlyItsComplicatedFull"

var _DualHostSupport_index = [...]uint8{0, 12, 20, 33, 46, 60, 64}

func (i DualHostSupport) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DualHostSupport_index)-1 {
		return "DualHostSupport(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DualHostSupport_name[_DualHostSupport_index[idx]:_DualHostSupport_index[idx+1]]
}
