// Code generated by "stringer -type FieldType -trimprefix FieldType"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldTypeString-0]
	_ = x[FieldTypeBool-1]
}

const _FieldType_name = "StringBool"

var _FieldType_index = [...]uint8{0, 6, 10}

func (i FieldType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FieldType_index)-1 {
		return "FieldType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldType_name[_FieldType_index[idx]:_FieldType_index[idx+1]]
}
