// Code generated by "stringer -type SupportLevel -trimprefix SupportLevel"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SupportLevelDeprecated-0]
	_ = x[SupportLevelNeedsVolunteer-1]
	_ = x[SupportLevelCommunity-2]
	_ = x[SupportLevelOfficial-3]
}

const _SupportLevel_name = "DeprecatedNeedsVolunteerCommunityOfficial"

var _SupportLevel_index = [...]uint8{0, 10, 24, 33, 41}

func (i SupportLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SupportLevel_index)-1 {
		return "SupportLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SupportLevel_name[_SupportLevel_index[idx]:_SupportLevel_index[idx+1]]
}
