version: "2"

linters:
  default: standard
  disable:
    - errcheck
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - durationcheck
    - godot
    - predeclared
# 2026-05-02: Temporary exclusions
  exclusions:
    rules:
      - linters:
          - govet
        text: "inline: cannot inline: type parameter inference is not yet supported"
