useGitIgnore: true
dirs:
  - documentation
files:
  - README.md
  - SECURITY.md
ignorePatterns:
  - pattern: '.*?plain=1$'
  - pattern: '.*.md#$'
  - pattern: '^https://cloud.digitalocean.com/account/api/tokens'
  - pattern: '^https://cloud.digitalocean.com/settings/applications'
  - pattern: '^https://dns.hetzner.com/settings/api-token'
  - pattern: '^https://github.com/StackExchange/dnscontrol/settings/.*$'
  - pattern: '^https://gitlab.com/cafferata/dnscontrol/-/pipelines/new.*$'
  - pattern: '^https://my.easyname.com/en/account/api'
