# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: "true"
  branches:
    include:
    - master

jobs:

- job: "compile"
  container: golang:1.12
  steps:
  - script: |
      pwd
      go env
      go run build/build.go
