variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.12' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

trigger:
  batch: "true"
  branches:
    include:
    - master

jobs:

- job: "compile"
  steps:
  - template: build/azure-pipelines/go-env.yaml
  - script: |
      pwd
      go env
      go run build/build.go
    workingDirectory: '$(modulePath)'
