// Code generated by "stringer -type=State"; DO NOT EDIT.

package route53

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateStart-0]
	_ = x[StateQuoted-1]
	_ = x[StateBackslash-2]
	_ = x[StateQuotedBackslash-3]
	_ = x[StateWantSpace-4]
	_ = x[StateWantSpaceOrQuote-5]
}

const _State_name = "StateStartStateQuotedStateBackslashStateQuotedBackslashStateWantSpaceStateWantSpaceOrQuote"

var _State_index = [...]uint8{0, 10, 21, 35, 55, 69, 90}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
