// Code generated by "stringer -type=Verb"; DO NOT EDIT.

package diff2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CREATE-1]
	_ = x[CHANGE-2]
	_ = x[DELETE-3]
	_ = x[REPORT-4]
}

const _Verb_name = "CREATECHANGEDELETEREPORT"

var _Verb_index = [...]uint8{0, 6, 12, 18, 24}

func (i Verb) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Verb_index)-1 {
		return "Verb(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verb_name[_Verb_index[idx]:_Verb_index[idx+1]]
}
