/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Providers:

var REG_NONE = NewRegistrar("none");
var DNS_BIND = NewDnsProvider("bind");

// Domains:

D("example.com", REG_NONE, DnsProvider(DNS_BIND),
    A("@", "1.2.3.4")
);

