/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Providers:

var REG_CLOUDFLAREAPI = NewRegistrar("cloudflare");
var DNS_CLOUDFLAREAPI = NewDnsProvider("cloudflare");

// Domains:

D("example.com", REG_CLOUDFLAREAPI, DnsProvider(DNS_CLOUDFLAREAPI),
    DefaultTTL(3600),
    A("@", "192.0.2.1"),
    A("www", "192.0.2.1"),
    MX("@", 10, "mx.example.com."),
);

