/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Providers:

var REG_CLOUDFLAREAPI = NewRegistrar("cloudflare");
var DNS_CLOUDFLAREAPI = NewDnsProvider("cloudflare");

// Domains:

D("example.com", REG_CLOUDFLAREAPI, DnsProvider(DNS_CLOUDFLAREAPI),
    A("@", "1.2.3.4")
);

D("example.org", REG_CLOUDFLAREAPI, DnsProvider(DNS_CLOUDFLAREAPI),
    A("@", "1.2.3.4")
);

