/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Providers:

var REG_NONE = NewRegistrar("none");

// Domains:

D("example.com", REG_NONE,
    A("@", "1.2.3.4")
);

