// Code generated by "go run types_generate.go"; DO NOT EDIT.

package rtypes

// // NS is the fields needed to store a DNS record of typeNS
// type NS struct {
// 	Ns
// }

// // A is the fields needed to store a DNS record of typeA
// type A struct {
// 	A [4]byte
// }

// // CNAME is the fields needed to store a DNS record of typeCNAME
// type CNAME struct {
// 	Target
// }

// // MX is the fields needed to store a DNS record of typeMX
// type MX struct {
// 	Preference
// 	Mx string
// }

// func init() {
// 	rtypectl.Register("A", rtypectl.RegisterOpts{
// 		FromRaw: FromRawA,
// 	})
// }
// func FromRawMX()