package create

import (
	"github.com/StackExchange/dnscontrol/v4/models"
	"github.com/StackExchange/dnscontrol/v4/providers/cloudflare/rtypes/rtypecfsingleredirect"
)

// Helper functions (one per rtype2.0) that create a RecordConfig of
// this type.
// In the future, this will be autogenerated.

// CloudFlareSingleRedirect creates a RecordConfig of type CloudFlareSingleRedirect.
func CloudFlareSingleRedirect(ttl uint32, origin, label string, items []any) (*models.RecordConfig, error) {
	r := &models.RecordConfig{TTL: ttl}
	rd, err := rtypecfsingleredirect.FromRawArgs(items, label)
	if err != nil {
		return nil, err
	}
	r.Seal(origin, label, rd)
	return r, nil
}
