on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.20", "1.21", "1.22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v -race ./...
