redirects:
  service-providers/providers: providers.md
  service-providers/providers/akamaiedgedns: provider/akamaiedgedns.md
  service-providers/providers/autodns: provider/autodns.md
  service-providers/providers/axfrddns: provider/axfrddns.md
  service-providers/providers/azure_dns: provider/azure_dns.md
  service-providers/providers/azure_private_dns: provider/azure_private_dns.md
  service-providers/providers/bind: provider/bind.md
  service-providers/providers/bunny_dns: provider/bunny_dns.md
  service-providers/providers/cloudflareapi: provider/cloudflareapi.md
  service-providers/providers/cloudns: provider/cloudns.md
  service-providers/providers/cscglobal: provider/cscglobal.md
  service-providers/providers/desec: provider/desec.md
  service-providers/providers/digitalocean: provider/digitalocean.md
  service-providers/providers/dnsimple: provider/dnsimple.md
  service-providers/providers/dnsmadeeasy: provider/dnsmadeeasy.md
  service-providers/providers/dnsoverhttps: provider/dnsoverhttps.md
  service-providers/providers/domainnameshop: provider/domainnameshop.md
  service-providers/providers/dynadot: provider/dynadot.md
  service-providers/providers/easyname: provider/easyname.md
  service-providers/providers/exoscale: provider/exoscale.md
  service-providers/providers/gandi_v5: provider/gandi_v5.md
  service-providers/providers/gcloud: provider/gcloud.md
  service-providers/providers/gcore: provider/gcore.md
  service-providers/providers/hedns: provider/hedns.md
  service-providers/providers/hetzner: provider/hetzner.md
  service-providers/providers/hexonet: provider/hexonet.md
  service-providers/providers/hostingde: provider/hostingde.md
  service-providers/providers/internetbs: provider/internetbs.md
  service-providers/providers/inwx: provider/inwx.md
  service-providers/providers/linode: provider/linode.md
  service-providers/providers/loopia: provider/loopia.md
  service-providers/providers/luadns: provider/luadns.md
  service-providers/providers/msdns: provider/msdns.md
  service-providers/providers/mythicbeasts: provider/mythicbeasts.md
  service-providers/providers/namecheap: provider/namecheap.md
  service-providers/providers/namedotcom: provider/namedotcom.md
  service-providers/providers/netcup: provider/netcup.md
  service-providers/providers/netlify: provider/netlify.md
  service-providers/providers/ns1: provider/ns1.md
  service-providers/providers/opensrs: provider/opensrs.md
  service-providers/providers/oracle: provider/oracle.md
  service-providers/providers/ovh: provider/ovh.md
  service-providers/providers/packetframe: provider/packetframe.md
  service-providers/providers/porkbun: provider/porkbun.md
  service-providers/providers/powerdns: provider/powerdns.md
  service-providers/providers/realtimeregister: provider/realtimeregister.md
  service-providers/providers/route53: provider/route53.md
  service-providers/providers/rwth: provider/rwth.md
  service-providers/providers/softlayer: provider/softlayer.md
  service-providers/providers/transip: provider/transip.md
  service-providers/providers/vultr: provider/vultr.md
