package models

import "github.com/StackExchange/dnscontrol/v4/providers/cloudflare/rtypes/rtypecfsingleredirect"

// Helper functions (one per rtype2.0) so that users don't need to
// deal with type assertions and conversions.
// In the future, this will be autogenerated.

func (rc *RecordConfig) AsCloudflareSingleRedirect() *rtypecfsingleredirect.SingleRedirect {
	return rc.Rdata.(*rtypecfsingleredirect.SingleRedirect)
}
