package models

// Helper functions (one per rtype2.0) so that users don't need to
// deal with type assertions and conversions.
// In the future, this will be autogenerated.

import (
	"github.com/StackExchange/dnscontrol/v4/providers/cloudflare/rtypes/rtypesingleredirect"
	"github.com/StackExchange/dnscontrol/v4/rtypes/rtypemx"
)

func (rc *RecordConfig) AsMX() *rtypemx.MX {
	return rc.Rdata.(*rtypemx.MX)
}

func (rc *RecordConfig) AsSingleRedirect() *rtypesingleredirect.SingleRedirect {
	return rc.Rdata.(*rtypesingleredirect.SingleRedirect)
}
